# Generated by config_brpc.sh, don't modify manually
SYSTEM=Linux
HDRS=/usr/include/ ./src/ullib/include
LIBS=/usr/lib64
PROTOC=/usr/bin/protoc
PROTOBUF_HDR=/usr/include/
CC=gcc
CXX=g++
GCC_VERSION=40805
STATIC_LINKINGS=/data/github/incubator-brpc/src/ullib/lib/libullib.a 
DYNAMIC_LINKINGS=-lpthread -lssl -lcrypto -ldl -lz -lrt -lgflags -lprotobuf -lleveldb
CPPFLAGS=-DCOMLOG -DBRPC_WITH_GLOG=0 -DGFLAGS_NS=gflags -g
ifeq ($(NEED_LIBPROTOC), 1)
    DYNAMIC_LINKINGS+=-lprotoc
endif
NEED_GPERFTOOLS=0
ifeq ($(NEED_GPERFTOOLS), 1)
    $(error "Fail to find gperftools")
endif
ifeq ($(NEED_GTEST), 1)
    $(error "Fail to find gtest")
endif
